# Use the rocker/rstudio base image
FROM rocker/rstudio:{{rocker_rstudio_tag}}


# Install system dependencies
RUN {{{system_dependencies}}}


# Set the CRAN repository
RUN echo 'options(repos = c(CRAN = "https://packagemanager.posit.co/cran/latest"))' > /usr/local/lib/R/etc/Rprofile.site

# Copy the analysis directory and renv.lock file to the container
COPY . /home/rstudio/.
COPY renv.lock /home/rstudio/renv.lock

# Set the working directory to the analysis folder
WORKDIR /home/rstudio/

# Install renv
RUN R -e "install.packages('renv')"

# Expose the RStudio Server port
EXPOSE {{port}}
# Change ownership of the analysis directory to the rstudio user
RUN chown -R rstudio:rstudio /home/rstudio

# Set up environment variables for RStudio
ENV USER {{username}}
ENV PASSWORD {{password}}
